// 倉庫番關卡集
// 前 3 關：手刻入門教學
// 其餘：David W. Skinner — Microban I & II (public domain)，依最少推動次數排序
// 全部關卡已過 BFS solver 驗證

const LEVELS = [
  {
    name: "第 1 關 · 試試看（1 推）",
    difficulty: "easy",
    optimalPushes: 1,
    source: "Tutorial #1",
    map: [
      "#####",
      "#   #",
      "#@$.#",
      "#   #",
      "#####",
    ],
  },
  {
    name: "第 2 關 · 多推一格（2 推）",
    difficulty: "easy",
    optimalPushes: 2,
    source: "Tutorial #2",
    map: [
      "######",
      "#    #",
      "#@$ .#",
      "#    #",
      "######",
    ],
  },
  {
    name: "第 3 關 · 連推三下（3 推）",
    difficulty: "easy",
    optimalPushes: 3,
    source: "Tutorial #3",
    map: [
      "#####",
      "#.  #",
      "#   #",
      "#$  #",
      "#@  #",
      "#####",
    ],
  },
  {
    name: "第 4 關 · 連推四下（4 推）",
    difficulty: "easy",
    optimalPushes: 4,
    source: "Tutorial #4",
    map: [
      "##########",
      "#        #",
      "#.   $ @ #",
      "#        #",
      "##########",
    ],
  },
  {
    name: "第 5 關 · 轉個彎（4 推）",
    difficulty: "easy",
    optimalPushes: 4,
    source: "Tutorial #5",
    map: [
      "######",
      "#.   #",
      "#    #",
      "#    #",
      "# $  #",
      "# @  #",
      "######",
    ],
  },
  {
    name: "第 6 關 · 最少 5 推",
    difficulty: "easy",
    optimalPushes: 5,
    source: "Microban I #21",
    map: [
      "####",
      "#  ####",
      "# . . #",
      "# $$#@#",
      "##    #",
      " ######",
    ],
  },
  {
    name: "第 7 關 · 最少 5 推",
    difficulty: "easy",
    optimalPushes: 5,
    source: "Microban I #30",
    map: [
      "####",
      "#  ###",
      "# $$ #",
      "#... #",
      "# @$ #",
      "#   ##",
      "#####",
    ],
  },
  {
    name: "第 8 關 · 最少 6 推",
    difficulty: "easy",
    optimalPushes: 6,
    source: "Microban I #5",
    map: [
      " #######",
      " #     #",
      " # .$. #",
      "## $@$ #",
      "#  .$. #",
      "#      #",
      "########",
    ],
  },
  {
    name: "第 9 關 · 最少 6 推",
    difficulty: "easy",
    optimalPushes: 6,
    source: "Microban I #7",
    map: [
      "#######",
      "#     #",
      "# .$. #",
      "# $.$ #",
      "# .$. #",
      "# $.$ #",
      "#  @  #",
      "#######",
    ],
  },
  {
    name: "第 10 關 · 最少 6 推",
    difficulty: "easy",
    optimalPushes: 6,
    source: "Microban I #31",
    map: [
      "  ####",
      " ##  #",
      "##@$.##",
      "# $$  #",
      "# . . #",
      "###   #",
      "  #####",
    ],
  },
  {
    name: "第 11 關 · 最少 6 推",
    difficulty: "easy",
    optimalPushes: 6,
    source: "Microban I #56",
    map: [
      "#####",
      "#   ###",
      "#  $  #",
      "##* . #",
      " #   @#",
      " ######",
    ],
  },
  {
    name: "第 12 關 · 最少 6 推",
    difficulty: "easy",
    optimalPushes: 6,
    source: "Microban II #9",
    map: [
      "######",
      "#    #",
      "# #$@#",
      "# .*.#",
      "# #$ #",
      "#    #",
      "######",
    ],
  },
  {
    name: "第 13 關 · 最少 6 推",
    difficulty: "easy",
    optimalPushes: 6,
    source: "Microban II #25",
    map: [
      " #####",
      "##   ##",
      "# .$. #",
      "# $#$ #",
      "# .$. #",
      "#    ##",
      "## @##",
      " ####",
    ],
  },
  {
    name: "第 14 關 · 最少 7 推",
    difficulty: "easy",
    optimalPushes: 7,
    source: "Microban I #4",
    map: [
      "########",
      "#      #",
      "# .**$@#",
      "#      #",
      "#####  #",
      "    ####",
    ],
  },
  {
    name: "第 15 關 · 最少 7 推",
    difficulty: "easy",
    optimalPushes: 7,
    source: "Microban I #25",
    map: [
      " ####",
      " #  ###",
      " # $$ #",
      "##... #",
      "#  @$ #",
      "#   ###",
      "#####",
    ],
  },
  {
    name: "第 16 關 · 最少 7 推",
    difficulty: "easy",
    optimalPushes: 7,
    source: "Microban I #40",
    map: [
      " #####",
      " #   #",
      "##   ##",
      "# $$$ #",
      "# .+. #",
      "#######",
    ],
  },
  {
    name: "第 17 關 · 最少 7 推",
    difficulty: "easy",
    optimalPushes: 7,
    source: "Microban II #2",
    map: [
      " #####",
      " #   #",
      "##.# #",
      "#  @ #",
      "#  $ #",
      "# #*##",
      "#   #",
      "#####",
    ],
  },
  {
    name: "第 18 關 · 最少 7 推",
    difficulty: "easy",
    optimalPushes: 7,
    source: "Microban II #10",
    map: [
      "#####",
      "#   #",
      "#   ###",
      "#$$$@ #",
      "#...  #",
      "#######",
    ],
  },
  {
    name: "第 19 關 · 最少 8 推",
    difficulty: "easy",
    optimalPushes: 8,
    source: "Microban I #1",
    map: [
      "####",
      "# .#",
      "#  ###",
      "#*@  #",
      "#  $ #",
      "#  ###",
      "####",
    ],
  },
  {
    name: "第 20 關 · 最少 8 推",
    difficulty: "easy",
    optimalPushes: 8,
    source: "Microban I #34",
    map: [
      "  ####",
      "###  ####",
      "#       #",
      "#@$***. #",
      "#       #",
      "#########",
    ],
  },
  {
    name: "第 21 關 · 最少 8 推",
    difficulty: "easy",
    optimalPushes: 8,
    source: "Microban I #38",
    map: [
      "##########",
      "#        #",
      "# ##.### #",
      "# # $$ . #",
      "# . @$## #",
      "#####    #",
      "    ######",
    ],
  },
  {
    name: "第 22 關 · 最少 8 推",
    difficulty: "easy",
    optimalPushes: 8,
    source: "Microban I #46",
    map: [
      " ######",
      "##    #",
      "#  ## #",
      "# # $ #",
      "#  * .#",
      "## #@##",
      " #   #",
      " #####",
    ],
  },
  {
    name: "第 23 關 · 最少 8 推",
    difficulty: "easy",
    optimalPushes: 8,
    source: "Microban I #51",
    map: [
      "####",
      "#  ###",
      "#    ###",
      "#  $*@ #",
      "### .# #",
      "  #    #",
      "  ######",
    ],
  },
  {
    name: "第 24 關 · 最少 8 推",
    difficulty: "easy",
    optimalPushes: 8,
    source: "Microban I #52",
    map: [
      "  ####",
      "### @#",
      "#  $ #",
      "#  *.#",
      "#  *.#",
      "#  $ #",
      "###  #",
      "  ####",
    ],
  },
  {
    name: "第 25 關 · 最少 8 推",
    difficulty: "easy",
    optimalPushes: 8,
    source: "Microban I #67",
    map: [
      "#####",
      "#   ##",
      "# #  #",
      "#@$*.##",
      "##  . #",
      " # $# #",
      " ##   #",
      "  #####",
    ],
  },
  {
    name: "第 26 關 · 最少 9 推",
    difficulty: "medium",
    optimalPushes: 9,
    source: "Microban I #17",
    map: [
      "#####",
      "# @ #",
      "#...#",
      "#$$$##",
      "#    #",
      "#    #",
      "######",
    ],
  },
  {
    name: "第 27 關 · 最少 9 推",
    difficulty: "medium",
    optimalPushes: 9,
    source: "Microban I #28",
    map: [
      "#####",
      "#   #",
      "# @ #",
      "# $$###",
      "##. . #",
      " #    #",
      " ######",
    ],
  },
  {
    name: "第 28 關 · 最少 9 推",
    difficulty: "medium",
    optimalPushes: 9,
    source: "Microban II #14",
    map: [
      " ####",
      "##  ###",
      "# .$  #",
      "#@.$  #",
      "# .$ ##",
      "##  ##",
      " ####",
    ],
  },
  {
    name: "第 29 關 · 最少 10 推",
    difficulty: "medium",
    optimalPushes: 10,
    source: "Microban I #9",
    map: [
      "#####",
      "#.  ##",
      "#@$$ #",
      "##   #",
      " ##  #",
      "  ##.#",
      "   ###",
    ],
  },
  {
    name: "第 30 關 · 最少 10 推",
    difficulty: "medium",
    optimalPushes: 10,
    source: "Microban I #26",
    map: [
      " #####",
      " # @ #",
      " #   #",
      "###$ #",
      "# ...#",
      "# $$ #",
      "###  #",
      "  ####",
    ],
  },
  {
    name: "第 31 關 · 最少 10 推",
    difficulty: "medium",
    optimalPushes: 10,
    source: "Microban II #11",
    map: [
      "######",
      "#.#  #",
      "#@$$ #",
      "#..$ #",
      "##   #",
      " #####",
    ],
  },
  {
    name: "第 32 關 · 最少 10 推",
    difficulty: "medium",
    optimalPushes: 10,
    source: "Microban II #49",
    map: [
      " #####",
      "##   #",
      "#    #",
      "# .$.##",
      "##$#$ #",
      " #.$. #",
      " #    #",
      " # @ ##",
      " #####",
    ],
  },
  {
    name: "第 33 關 · 最少 11 推",
    difficulty: "medium",
    optimalPushes: 11,
    source: "Microban I #45",
    map: [
      "######",
      "#... #",
      "#  $ #",
      "# #$##",
      "#  $ #",
      "#  @ #",
      "######",
    ],
  },
  {
    name: "第 34 關 · 最少 11 推",
    difficulty: "medium",
    optimalPushes: 11,
    source: "Microban II #8",
    map: [
      "########",
      "#   @  #",
      "#   *  #",
      "###.$###",
      "  # * #",
      "  #   #",
      "  #####",
    ],
  },
  {
    name: "第 35 關 · 最少 12 推",
    difficulty: "medium",
    optimalPushes: 12,
    source: "Microban I #15",
    map: [
      "     ###",
      "######@##",
      "#    .* #",
      "#   #   #",
      "#####$# #",
      "    #   #",
      "    #####",
    ],
  },
  {
    name: "第 36 關 · 最少 12 推",
    difficulty: "medium",
    optimalPushes: 12,
    source: "Microban I #103",
    map: [
      "  #####",
      "  # . ##",
      "### $  #",
      "# . $#@#",
      "# #$ . #",
      "#  $ ###",
      "## . #",
      " #####",
    ],
  },
  {
    name: "第 37 關 · 最少 13 推",
    difficulty: "medium",
    optimalPushes: 13,
    source: "Microban I #18",
    map: [
      "#######",
      "#     #",
      "#. .  #",
      "# ## ##",
      "#  $ #",
      "###$ #",
      "  #@ #",
      "  #  #",
      "  ####",
    ],
  },
  {
    name: "第 38 關 · 最少 13 推",
    difficulty: "medium",
    optimalPushes: 13,
    source: "Microban II #39",
    map: [
      " ######",
      "##    #",
      "#  ## #",
      "#@# $ #",
      "#  *..#",
      "## #$###",
      " #     #",
      " ###   #",
      "   #####",
    ],
  },
  {
    name: "第 39 關 · 最少 14 推",
    difficulty: "medium",
    optimalPushes: 14,
    source: "Microban I #82",
    map: [
      "#####",
      "#   ###",
      "# .   ##",
      "##*#$  #",
      "# .# $ #",
      "# @## ##",
      "#     #",
      "#######",
    ],
  },
  {
    name: "第 40 關 · 最少 14 推",
    difficulty: "medium",
    optimalPushes: 14,
    source: "Microban I #116",
    map: [
      "     #####",
      "   ###   #",
      "####.....#",
      "# @$$$$$ #",
      "#     # ##",
      "#####   #",
      "    #####",
    ],
  },
  {
    name: "第 41 關 · 最少 14 推",
    difficulty: "medium",
    optimalPushes: 14,
    source: "Microban II #38",
    map: [
      "  ######",
      "  #    #",
      "### ## #",
      "# ...  #",
      "#  $ ###",
      "# #$##",
      "#  $ #",
      "#  @ #",
      "######",
    ],
  },
  {
    name: "第 42 關 · 最少 14 推",
    difficulty: "medium",
    optimalPushes: 14,
    source: "Microban II #128",
    map: [
      "   #######",
      "  ##     ##",
      "###  ###  #",
      "#   #   # #",
      "#@$***. # #",
      "##      # #",
      " #### ##  #",
      "    #    ##",
      "    ######",
    ],
  },
  {
    name: "第 43 關 · 最少 15 推",
    difficulty: "medium",
    optimalPushes: 15,
    source: "Microban I #66",
    map: [
      "   ###",
      "   #@#",
      " ###$###",
      "##  .  ##",
      "#  # #  #",
      "# #   # #",
      "# #   # #",
      "# #   # #",
      "#  # #  #",
      "## $ $ ##",
      " ##. .##",
      "  #   #",
      "  #   #",
      "  #####",
    ],
  },
  {
    name: "第 44 關 · 最少 15 推",
    difficulty: "medium",
    optimalPushes: 15,
    source: "Microban II #64",
    map: [
      "#########",
      "#  ##   ##",
      "# $ $$*@ #",
      "#  # . # #",
      "## #. .  #",
      " #   #####",
      " #####",
    ],
  },
  {
    name: "第 45 關 · 最少 16 推",
    difficulty: "medium",
    optimalPushes: 16,
    source: "Microban I #20",
    map: [
      "#######",
      "#     ###",
      "#  @$$..#",
      "#### ## #",
      "  #     #",
      "  #  ####",
      "  #  #",
      "  ####",
    ],
  },
  {
    name: "第 46 關 · 最少 16 推",
    difficulty: "medium",
    optimalPushes: 16,
    source: "Microban II #6",
    map: [
      "   ####",
      "####  #",
      "#@.*  #",
      "#  #  ###",
      "####  $ #",
      "   #  # #",
      "   ##   #",
      "    #####",
    ],
  },
  {
    name: "第 47 關 · 最少 16 推",
    difficulty: "medium",
    optimalPushes: 16,
    source: "Microban II #90",
    map: [
      " #####",
      " #   #",
      " #   ##",
      " #$*$ #",
      "##. . #",
      "# .@.##",
      "# $*$#",
      "##   #",
      " #   #",
      " #####",
    ],
  },
  {
    name: "第 48 關 · 最少 16 推",
    difficulty: "medium",
    optimalPushes: 16,
    source: "Microban II #127",
    map: [
      "#####",
      "#@  ######",
      "#  $ #   #",
      "#.*.*. $ #",
      "#  $ #####",
      "##   #",
      " #####",
    ],
  },
  {
    name: "第 49 關 · 最少 18 推",
    difficulty: "medium",
    optimalPushes: 18,
    source: "Microban I #79",
    map: [
      " #########",
      " #    #  #",
      "## $#$#  #",
      "#  .$.@  #",
      "#  .#    #",
      "##########",
    ],
  },
  {
    name: "第 50 關 · 最少 18 推",
    difficulty: "medium",
    optimalPushes: 18,
    source: "Microban II #53",
    map: [
      " ######",
      " #    #",
      " #. ..##",
      "###$ @ #",
      "# $  $ #",
      "#   ####",
      "#####",
    ],
  },
  {
    name: "第 51 關 · 最少 19 推",
    difficulty: "hard",
    optimalPushes: 19,
    source: "Microban I #128",
    map: [
      "  #########",
      "###   #   #",
      "# * $ . . #",
      "#   $ ## ##",
      "####*#   #",
      " #  @  ###",
      " #   ###",
      " #####",
    ],
  },
  {
    name: "第 52 關 · 最少 20 推",
    difficulty: "hard",
    optimalPushes: 20,
    source: "Microban I #19",
    map: [
      "########",
      "#   .. #",
      "#  @$$ #",
      "##### ##",
      "   #  #",
      "   #  #",
      "   #  #",
      "   ####",
    ],
  },
  {
    name: "第 53 關 · 最少 21 推",
    difficulty: "hard",
    optimalPushes: 21,
    source: "Microban I #10",
    map: [
      "      #####",
      "      #.  #",
      "      #.# #",
      "#######.# #",
      "# @ $ $ $ #",
      "# # # # ###",
      "#       #",
      "#########",
    ],
  },
  {
    name: "第 54 關 · 最少 21 推",
    difficulty: "hard",
    optimalPushes: 21,
    source: "Microban I #61",
    map: [
      "########",
      "#      #",
      "# #### #",
      "# #...@#",
      "# ###$###",
      "# #     #",
      "#  $$ $ #",
      "####   ##",
      "   #.###",
      "   ###",
    ],
  },
  {
    name: "第 55 關 · 最少 22 推",
    difficulty: "hard",
    optimalPushes: 22,
    source: "Microban I #47",
    map: [
      "  #######",
      "###     #",
      "# $ $   #",
      "# ### #####",
      "# @ . .   #",
      "#   ###   #",
      "##### #####",
    ],
  },
  {
    name: "第 56 關 · 最少 22 推",
    difficulty: "hard",
    optimalPushes: 22,
    source: "Microban II #79",
    map: [
      "    ####",
      " ####  #",
      " #     #",
      "##.# # ##",
      "#@$ $#  #",
      "# .$    #",
      "##.$##  #",
      " #. #####",
      " ####",
    ],
  },
  {
    name: "第 57 關 · 最少 22 推",
    difficulty: "hard",
    optimalPushes: 22,
    source: "Microban II #93",
    map: [
      "    ####",
      "  ###  #",
      " ## .  #",
      "##     #",
      "# .$. ##",
      "# $ ###",
      "# .$####",
      "###    #",
      " ##$#  #",
      " #  #  #",
      " #  @ ##",
      " ###  #",
      "   ####",
    ],
  },
  {
    name: "第 58 關 · 最少 23 推",
    difficulty: "hard",
    optimalPushes: 23,
    source: "Microban II #43",
    map: [
      "     ####",
      "     # @##",
      "###### $ ##",
      "#  . # $  #",
      "#      $# #",
      "## ..#    #",
      " ##  ######",
      "  ####",
    ],
  },
  {
    name: "第 59 關 · 最少 24 推",
    difficulty: "hard",
    optimalPushes: 24,
    source: "Microban II #32",
    map: [
      "########",
      "#      #",
      "#    # #",
      "###..$.#",
      "  # #$##",
      "  #  @ #",
      "  ## $ #",
      "   # # #",
      "   #   #",
      "   #####",
    ],
  },
  {
    name: "第 60 關 · 最少 26 推",
    difficulty: "hard",
    optimalPushes: 26,
    source: "Microban I #70",
    map: [
      "#####",
      "# @ ####",
      "#      #",
      "# $ $$ #",
      "##$##  #",
      "#   ####",
      "# ..  #",
      "##..  #",
      " ###  #",
      "   ####",
    ],
  },
  {
    name: "第 61 關 · 最少 27 推",
    difficulty: "hard",
    optimalPushes: 27,
    source: "Microban II #27",
    map: [
      "#######",
      "#  +  #",
      "# *$* #",
      "#. # .#",
      "#  #  #",
      "#  #  #",
      "#  #  #",
      "# $#$ #",
      "#  #  #",
      "#######",
    ],
  },
  {
    name: "第 62 關 · 最少 28 推",
    difficulty: "hard",
    optimalPushes: 28,
    source: "Microban II #61",
    map: [
      "#####",
      "#   #",
      "#   ######",
      "#$$$$ $ @#",
      "#.....   #",
      "##########",
    ],
  },
  {
    name: "第 63 關 · 最少 29 推",
    difficulty: "hard",
    optimalPushes: 29,
    source: "Microban I #115",
    map: [
      "    #####",
      "#####   ####",
      "#     #    #",
      "#  #.....  #",
      "##  ## # ###",
      " #$$@$$$ #",
      " #     ###",
      " #######",
    ],
  },
  {
    name: "第 64 關 · 最少 30 推",
    difficulty: "hard",
    optimalPushes: 30,
    source: "Microban I #62",
    map: [
      "   ##########",
      "####    ##  #",
      "#  $$$....$@#",
      "#      ###  #",
      "#   #### ####",
      "#####",
    ],
  },
  {
    name: "第 65 關 · 最少 31 推",
    difficulty: "hard",
    optimalPushes: 31,
    source: "Microban I #131",
    map: [
      "#####",
      "#   #",
      "# . #",
      "#.@.###",
      "##.#  #",
      "#  $  #",
      "# $   #",
      "##$$  #",
      " #  ###",
      " #  #",
      " ####",
    ],
  },
  {
    name: "第 66 關 · 最少 32 推",
    difficulty: "hard",
    optimalPushes: 32,
    source: "Microban I #127",
    map: [
      "## ####",
      "####  ####",
      " # $ $.  #",
      "## #  .$ #",
      "#   ##.###",
      "#  $  . #",
      "# @ #   #",
      "#  ######",
      "####",
    ],
  },
  {
    name: "第 67 關 · 最少 33 推",
    difficulty: "hard",
    optimalPushes: 33,
    source: "Microban I #78",
    map: [
      " #######",
      "##     ##",
      "#  $ $  #",
      "# $ $ $ #",
      "## ### ####",
      " #@  .....#",
      " ##     ###",
      "  #######",
    ],
  },
  {
    name: "第 68 關 · 最少 35 推",
    difficulty: "hard",
    optimalPushes: 35,
    source: "Microban I #89",
    map: [
      "##########",
      "#   ##   #",
      "# $  $@# #",
      "#### # $ #",
      "   #.#  ##",
      " # #.# $#",
      " # #.   #",
      " # #.   #",
      "   ######",
    ],
  },
  {
    name: "第 69 關 · 最少 36 推",
    difficulty: "expert",
    optimalPushes: 36,
    source: "Microban I #130",
    map: [
      "#####  #####",
      "#   ####.. #",
      "# $$$      #",
      "#   $#  .. #",
      "### @#  ## #",
      "  #  ##    #",
      "  ##########",
    ],
  },
  {
    name: "第 70 關 · 最少 37 推",
    difficulty: "expert",
    optimalPushes: 37,
    source: "Microban I #69",
    map: [
      "####  ####",
      "#  ####  #",
      "#  #  #  #",
      "#  #    $##",
      "#  . .#$  #",
      "#@ ## # $ #",
      "#   . #   #",
      "###########",
    ],
  },
  {
    name: "第 71 關 · 最少 39 推",
    difficulty: "expert",
    optimalPushes: 39,
    source: "Microban I #16",
    map: [
      " ####",
      " #  ####",
      " #     ##",
      "## ##   #",
      "#. .# @$##",
      "#   # $$ #",
      "#  .#    #",
      "##########",
    ],
  },
  {
    name: "第 72 關 · 最少 40 推",
    difficulty: "expert",
    optimalPushes: 40,
    source: "Microban II #45",
    map: [
      "   ###  #####",
      "#### ####   #",
      "#  ###      #",
      "# ..  $$$$  #",
      "# ..  # @#  #",
      "#############",
      "      #  #",
    ],
  },
  {
    name: "第 73 關 · 最少 44 推",
    difficulty: "expert",
    optimalPushes: 44,
    source: "Microban I #60",
    map: [
      " #########",
      " #       #",
      "##@##### #",
      "#  #   # #",
      "#  #   $.#",
      "#  ##$##.#",
      "##$##  #.#",
      "#   $  #.#",
      "#   #  ###",
      "########",
    ],
  },
  {
    name: "第 74 關 · 最少 46 推",
    difficulty: "expert",
    optimalPushes: 46,
    source: "Microban II #87",
    map: [
      "     ####",
      "     #  ###",
      "    ## .  ##",
      "    #. .   #",
      "    #.  #@ #",
      "    ## ##  #",
      "   ##  #####",
      "  ## $ #",
      " ## $  #",
      "## $  ##",
      "# $  ##",
      "#   ##",
      "#####",
    ],
  },
  {
    name: "第 75 關 · 最少 47 推",
    difficulty: "expert",
    optimalPushes: 47,
    source: "Microban II #100",
    map: [
      " #######",
      " #     ##",
      " # ###  ####",
      " #   ##    #",
      " #  $ #### #",
      "####$ .....#",
      "#  #  #### #",
      "####$$#    #",
      " #  $ # ####",
      " #  @ # #",
      " # #### #",
      " #      #",
      " ########",
    ],
  },
  {
    name: "第 76 關 · 最少 50 推",
    difficulty: "expert",
    optimalPushes: 50,
    source: "Microban I #106",
    map: [
      " ########",
      " #      #",
      " #@   $ #",
      "## ###$ #",
      "# .....###",
      "# $ $ $  #",
      "###### # #",
      "     #   #",
      "     #####",
    ],
  },
  {
    name: "第 77 關 · 最少 51 推",
    difficulty: "expert",
    optimalPushes: 51,
    source: "Microban I #85",
    map: [
      "       ####",
      " #######  #",
      " # $      #",
      " #   $ $  #",
      " # ########",
      "## # .  #",
      "#  # #  #",
      "#  @ . ##",
      "## # # #",
      " #   . #",
      " #######",
    ],
  },
  {
    name: "第 78 關 · 最少 53 推",
    difficulty: "expert",
    optimalPushes: 53,
    source: "Microban I #87",
    map: [
      "     ####",
      "######  #",
      "#       #",
      "#  ... .#",
      "##$######",
      "# $  #",
      "#   $###",
      "##  $  #",
      " ## @  #",
      "  ######",
    ],
  },
  {
    name: "第 79 關 · 最少 60 推",
    difficulty: "expert",
    optimalPushes: 60,
    source: "Microban II #129",
    map: [
      "       ####",
      "########  #",
      "#     $   #",
      "#  ##.##  #",
      "##$##  . ##",
      " #  . $# ##",
      " # ###.#  #",
      " # ### @  #",
      " #   $ ####",
      " #  ####",
      " ####",
    ],
  },
  {
    name: "第 80 關 · 最少 68 推",
    difficulty: "expert",
    optimalPushes: 68,
    source: "Microban I #84",
    map: [
      "########",
      "#  ... #",
      "#  ### ##",
      "#  # $  #",
      "## #@$  #",
      " # # $  #",
      " # ### #####",
      " #         #",
      " #   ###   #",
      " ##### #####",
    ],
  },
];

window.LEVELS = LEVELS;
